server {
    listen 80;
    server_name lichess-tailor.mobeigi.io;

    absolute_redirect off;

    root /var/www/html;
    index index.php;

    location = /style.user.css {
        rewrite ^ /style.php last;
    }

    location ~ \.php$ {
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location / {
        autoindex off;
        try_files $uri $uri/ =404;
    }
}
