<?php
declare(strict_types=1);
ini_set('display_errors', '0');

header('Content-Type: text/css; charset=utf-8');
header('Cache-Control: public, max-age=86400');

function validateHex(mixed $val, string $default): string
{
    return (is_string($val) && preg_match('/^[0-9a-fA-F]{6}$/', $val))
        ? strtolower($val)
        : $default;
}

function validateAlpha(mixed $val, int $default): int
{
    return is_numeric($val) ? max(0, min(100, (int) $val)) : $default;
}

function toRgba(string $hex, int $alpha): string
{
    $r = hexdec(substr($hex, 0, 2));
    $g = hexdec(substr($hex, 2, 2));
    $b = hexdec(substr($hex, 4, 2));
    $a = number_format($alpha / 100, 2, '.', '');
    return "rgba($r, $g, $b, $a)";
}

// Parse and validate inputs — defaults match the Walnut preset
$sq1    = validateHex  ($_GET['sq1']    ?? 'edd6b0', 'edd6b0');
$sq1a   = validateAlpha($_GET['sq1a']   ?? 100,       100);
$sq2    = validateHex  ($_GET['sq2']    ?? 'b88762', 'b88762');
$sq2a   = validateAlpha($_GET['sq2a']   ?? 100,       100);
$lm     = validateHex  ($_GET['lm']     ?? 'f6eb72', 'f6eb72');
$lma    = validateAlpha($_GET['lma']    ?? 60,        60);
$sel    = validateHex  ($_GET['sel']    ?? '5aa7cc', '5aa7cc');
$sela   = validateAlpha($_GET['sela']   ?? 60,        60);
$md     = validateHex  ($_GET['md']     ?? '573017', '573017');
$mda    = validateAlpha($_GET['mda']    ?? 60,        60);
$mdmode = in_array($_GET['mdmode'] ?? '', ['dot', 'square'], true)
    ? $_GET['mdmode']
    : 'dot';
$oc     = validateHex  ($_GET['oc']     ?? 'ff7d7d', 'ff7d7d');
$oca    = validateAlpha($_GET['oca']    ?? 60,        60);
$pm     = validateHex  ($_GET['pm']     ?? 'bb37bc', 'bb37bc');
$pma    = validateAlpha($_GET['pma']    ?? 60,        60);

// Convert to rgba strings
$sq1rgba = toRgba($sq1, $sq1a);
$sq2rgba = toRgba($sq2, $sq2a);
$lmRgba  = toRgba($lm,  $lma);
$selRgba = toRgba($sel,  $sela);
$mdRgba  = toRgba($md,   $mda);
$ocRgba  = toRgba($oc,   $oca);
$pmRgba  = toRgba($pm,   $pma);

// Build 8×8 checkerboard SVG board pattern
$svg = implode("\n", [
    '<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
    '<svg xmlns="http://www.w3.org/2000/svg" xmlns:x="http://www.w3.org/1999/xlink"',
    '     viewBox="0 0 8 8" shape-rendering="crispEdges">',
    '<g id="a">',
    '  <g id="b">',
    '    <g id="c">',
    '      <g id="d">',
    "        <rect width=\"1\" height=\"1\" id=\"e\" fill=\"{$sq1rgba}\"/>",
    '        <use x="1" y="1" href="#e" x:href="#e"/>',
    "        <rect y=\"1\" width=\"1\" height=\"1\" id=\"f\" fill=\"{$sq2rgba}\"/>",
    '        <use x="1" y="-1" href="#f" x:href="#f"/>',
    '      </g>',
    '      <use x="2" href="#d" x:href="#d"/>',
    '    </g>',
    '    <use x="4" href="#c" x:href="#c"/>',
    '  </g>',
    '  <use y="2" href="#b" x:href="#b"/>',
    '</g>',
    '<use y="4" href="#a" x:href="#a"/>',
    '</svg>',
]);

$b64 = base64_encode($svg);

// Move destination style
$mdCss = $mdmode === 'dot'
    ? "background: radial-gradient({$mdRgba} 19%, rgba(0, 0, 0, 0) 20%) !important;"
    : "background: unset !important;\n      background-color: {$mdRgba} !important;";

echo <<<CSS
/* ==UserStyle==
@name           Lichess Tailor style for lichess.org
@namespace      github.com/mobeigi/lichess-tailor
@version        1.0.0
@description    Custom board colours and overlay highlights for lichess.org, generated by Lichess Tailor.
@author         Mo Beigi
==/UserStyle== */

@-moz-document domain("lichess.org") {
    cg-board::before {
      background-color: {$sq1rgba} !important;
      background-image: url('data:image/svg+xml;base64,{$b64}') !important;
      filter: unset !important;
    }

    cg-wrap coords:nth-child(odd) coord:nth-child(odd),
    cg-wrap.orientation-black coords:nth-child(odd) coord:nth-child(even),
    cg-wrap coords.files:nth-child(even) coord:nth-child(odd),
    cg-wrap.orientation-black coords.files:nth-child(even) coord:nth-child(even) {
      color: {$sq1rgba} !important;
    }

    cg-wrap coords:nth-child(odd) coord:nth-child(even),
    cg-wrap.orientation-black coords:nth-child(odd) coord:nth-child(odd),
    cg-wrap coords.files:nth-child(even) coord:nth-child(even),
    cg-wrap.orientation-black coords.files:nth-child(even) coord:nth-child(odd) {
      color: {$sq2rgba} !important;
    }

    cg-board square.last-move {
      background-color: {$lmRgba} !important;
    }

    cg-board square.selected {
      background-color: {$selRgba} !important;
    }

    cg-board square.move-dest, cg-board square.premove-dest {
      {$mdCss}
    }

    cg-board square.oc {
      background: unset !important;
      background-color: {$ocRgba} !important;
    }

    cg-board square.current-premove, cg-board square.last-premove {
      background-color: {$pmRgba} !important;
    }
}
CSS;
